import type { Metadata } from "next";
import { DM_Sans, Fraunces, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";
import { Toaster } from "sonner";
import AuthSyncer from "@/components/common/AuthSyncer"; 

const uiSans = DM_Sans({
  variable: "--font-ui",
  subsets: ["latin"],
});

const display = Fraunces({
  variable: "--font-display",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${uiSans.variable} ${display.variable} ${geistMono.variable} bg-bg font-body text-text`}
      >
        <AuthSyncer />
        <div className="relative flex min-h-screen flex-col">
          <Header />
          <main className="flex-1">
            <Toaster />
            <div className="animate-fadeIn">
              {children}
            </div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
