import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";
import { useEffect } from "react";
import { signOut } from "../lib/firebase/auth"; // your signOut function
import AuthSyncer from "@/components/common/AuthSyncer"; 
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../lib/firebase/firebaseConfig";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <AuthSyncer /> 
        <div className="relative flex min-h-screen flex-col">
          <Header />
          <main className="flex-1">{children}</main>
          
          <Footer/>
        </div>
      </body>
    </html>
  );
}
